[package]
name = "genders"
version = "0.1.0"
authors = ["Samuel <haveachillday@gmail.com>"]
description = "..."
license = "..."
repository = "https://github.com/DoubleCouponDay/genders"
[dependencies]
