[package]
name = "genders"
version = "0.1.3"
authors = ["Samuel <haveachillday@gmail.com>", "Izzy <izzy@lskh.io>"]
description = "An extremely forward thinking Gender crate"
license = "GLWPL"
repository = "https://github.com/DoubleCouponDay/genders"
[dependencies]
