[package]
name = "genders"
version = "0.1.2"
authors = ["Samuel <haveachillday@gmail.com>"]
description = "enumerate genders in rust."
license = "WTFPL"
repository = "https://github.com/DoubleCouponDay/genders"
[dependencies]
